_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.12.2
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 75
                - 77
                - 105
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 75
                - 77
                - 105
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.2
            "5": 0.19.7
            "6": 4.44.0
            "8":
                - 5
            "12": 0.19.7
            "13": darwin-arm64
architecture:
    value: DySimGCF
dataset:
    value: Ml-100k
epochs:
    value: 1001
learning_rate:
    value: 0.001
